config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  protect_from_forgery with: :exception

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find params[:id]
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to articles_path
    else
      redirect_to new_article_path(@article.id)
    end
  end


  def edit
    @article = Article.find params[:id]
  end

  def update
    @article = Article.find params[:id]
    if @article.update_attributes(article_params)
      redirect_to articles_path
    else
      redirect_to edit_article_path(@article.id)
    end
  end

  def destroy
    @article = Article.find params[:id]

    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :text
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>2</h1>
<%= form_for @article do |f| %>
  <%= f.label "title" %>
<%= f.text_field :title %>
<br>
<%= f.label "text" %>
<%= f.text_area :text %>
<br>
<%= f.submit "save" %>
<% end %>

app/views/articles/index.html.erb
Comming soon

<br>

<%= link_to "new", new_article_path %>
<br>

<br>
<table>
  <th>ID</th>
  <th>Title</th>
  <th>Text</th>
  <th></th>
  <th></th>
  <th></th>
  <% @articles.each do |artcile| %>
    <tr>
      <td>
       <%= artcile.id %>
      </td>
      <td>
        <%= artcile.title %>
      </td>
      <td>
       <%= artcile.text %>
      </td>
      <td>
        <%= link_to "show", article_path(artcile.id) %>
      </td>
      <td>
        <%= link_to "edit", edit_article_path(artcile.id) %>
      </td>
      <td>
        <%=
          link_to "delete",
                   article_path(artcile.id),
                   method: :delete,
                   data: { confirm: "Are you sure?" }
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>2</h1>
<%= form_for @article do |f| %>
  <%= f.label "title" %>
  <%= f.text_field :title %>
  <br>
  <%= f.label "text" %>
  <%= f.text_area :text %>
  <br>
  <%= f.submit "save" %>
<% end %>

app/views/articles/show.html.erb
<h1> Arikel <%= @article.id %> </h1>
<br>
<h2> <%= @article.title %> </h2>
<%= link_to "back", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>